package telas;

import Quartos.*;
import javax.swing.DefaultComboBoxModel;

public class EscolherQuartoManu extends javax.swing.JFrame {

    /**
     * Creates new form EscolherQuartoManu
     */
    public EscolherQuartoManu(ListaQuarto quarto, int idServico) {
        this.quarto = quarto;
        initComponents();
        setLocationRelativeTo(null);
        this.idServico = idServico;
        switch(idServico){
            case 1:
                this.tituloServico.setText("Escolha o quarto a ser limpo");
                break;
            case 2:
                this.tituloServico.setText("Escolha o quarto que precisa de troca de chuveiro");
                break;
            case 3:
                this.tituloServico.setText("Escolha o quarto que precisa de toalhas");
                break;
            case 4:
                this.tituloServico.setText("Escolha o quarto que precisa de atendimento");
                break;
            case 5:
                this.tituloServico.setText("Escolha o quarto que a Hidro precisa ser limpa");
                break;
            case 6:
                this.tituloServico.setText("Escolha o quarto que precisa de atendimento do Mordomo");
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoVoltar = new javax.swing.JButton();
        tituloServico = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        msgErro = new javax.swing.JLabel();
        escolherQuarto = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botaoVoltar.setText("Voltar");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        jButton1.setText("Solicitar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        escolherQuarto.setModel(new DefaultComboBoxModel(this.quarto.quartoNums()));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botaoVoltar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(escolherQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tituloServico, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(msgErro, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botaoVoltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tituloServico, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(escolherQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(msgErro, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int numQ = this.escolherQuarto.getSelectedIndex();
        
        switch(this.idServico){
            case 1:
                this.quarto.getQuarto(numQ).limpar();
                this.dispose();
                break;
            case 2:
                this.quarto.getQuarto(numQ).TrocarChuveiro();
                this.dispose();
                break;
            case 3:
                this.quarto.getQuarto(numQ).AbastecerToalha();
                this.dispose();
                break;
            case 4:
                if(this.quarto.getQuarto(numQ) instanceof QuartoConfort quartoConfort){
                    quartoConfort.chamarServico();
                    this.dispose();
                } else {
                    this.msgErro.setText("Esse serviço não está disponível para esse quarto");
                }
                break;

            case 5:
                if(this.quarto.getQuarto(numQ) instanceof QuartoConfort quartoConfort && quartoConfort.isHidro()){
                    quartoConfort.limparHidro();
                    this.dispose();
                } else {
                    this.msgErro.setText("Esse serviço não está disponível para esse quarto");
                }
                break;
            case 6:
                if(this.quarto.getQuarto(numQ) instanceof QuartoMaster quartoMaster && quartoMaster.isMordomo()){
                    quartoMaster.chamarMordomo();
                    this.dispose();
                } else {
                    this.msgErro.setText("Esse serviço não está disponível para esse quarto");
                }
                break;
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_botaoVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    
    private int idServico;
    private ListaQuarto quarto;    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JComboBox<String> escolherQuarto;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel msgErro;
    private javax.swing.JLabel tituloServico;
    // End of variables declaration//GEN-END:variables
}
