package telas;

import Quartos.ListaQuarto;

public class EscolherTipoQuarto extends javax.swing.JFrame {

    /**
     * Creates new form CriarQuarto
     * @param lista
     */
    
    public EscolherTipoQuarto(ListaQuarto lista) {
        initComponents();
        setLocationRelativeTo(null);
        this.listQuarto = lista;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        BotaoQuartoSimples = new javax.swing.JButton();
        BotaoQuartoConfort = new javax.swing.JButton();
        BotaoQuartoMaster = new javax.swing.JButton();
        BotaoVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Titulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Escolher tipo de quarto");

        BotaoQuartoSimples.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BotaoQuartoSimples.setText("Quarto Simples");
        BotaoQuartoSimples.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoQuartoSimplesActionPerformed(evt);
            }
        });

        BotaoQuartoConfort.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BotaoQuartoConfort.setText("Quarto Confort");
        BotaoQuartoConfort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoQuartoConfortActionPerformed(evt);
            }
        });

        BotaoQuartoMaster.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BotaoQuartoMaster.setText("Quarto Master");
        BotaoQuartoMaster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoQuartoMasterActionPerformed(evt);
            }
        });

        BotaoVoltar.setText("Voltar");
        BotaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BotaoVoltar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 58, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BotaoQuartoSimples, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotaoQuartoConfort, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotaoQuartoMaster, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BotaoVoltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Titulo)
                .addGap(18, 18, 18)
                .addComponent(BotaoQuartoSimples)
                .addGap(18, 18, 18)
                .addComponent(BotaoQuartoConfort)
                .addGap(18, 18, 18)
                .addComponent(BotaoQuartoMaster)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoVoltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_BotaoVoltarActionPerformed
        
    private void BotaoQuartoSimplesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoQuartoSimplesActionPerformed
        new CriarQuarto(listQuarto, 1).setVisible(true);
    }//GEN-LAST:event_BotaoQuartoSimplesActionPerformed

    private void BotaoQuartoConfortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoQuartoConfortActionPerformed
        new CriarQuarto(listQuarto, 2).setVisible(true);
    }//GEN-LAST:event_BotaoQuartoConfortActionPerformed

    private void BotaoQuartoMasterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoQuartoMasterActionPerformed
        new CriarQuarto(listQuarto, 3).setVisible(true);
    }//GEN-LAST:event_BotaoQuartoMasterActionPerformed

    /**
     * @param args the command line arguments
     */
    private ListaQuarto listQuarto;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoQuartoConfort;
    private javax.swing.JButton BotaoQuartoMaster;
    private javax.swing.JButton BotaoQuartoSimples;
    private javax.swing.JButton BotaoVoltar;
    private javax.swing.JLabel Titulo;
    // End of variables declaration//GEN-END:variables
}
