package telas;

import Quartos.*;

public class PainelManutencao extends javax.swing.JFrame {

    /**
     * Creates new form PainelManutencao
     * @param quarto
     */
    public PainelManutencao(ListaQuarto quarto) {
        initComponents();
        setLocationRelativeTo(null);
        this.quarto = quarto;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        botaoVoltar = new javax.swing.JToggleButton();
        botaoLimpeza = new javax.swing.JButton();
        botaoTrocarChuveiro = new javax.swing.JButton();
        botaoAbastecerToalha = new javax.swing.JButton();
        botaoServico = new javax.swing.JButton();
        botaoLimparHidro = new javax.swing.JButton();
        botaoMordomo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Painel Manutenção");

        botaoVoltar.setText("Voltar");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        botaoLimpeza.setText("Chamar a limpeza");
        botaoLimpeza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimpezaActionPerformed(evt);
            }
        });

        botaoTrocarChuveiro.setText("Solicitar troca de chuveiro");
        botaoTrocarChuveiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoTrocarChuveiroActionPerformed(evt);
            }
        });

        botaoAbastecerToalha.setText("Abastecer toalhas");
        botaoAbastecerToalha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAbastecerToalhaActionPerformed(evt);
            }
        });

        botaoServico.setText("Charmar Serviço de Quarto");
        botaoServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoServicoActionPerformed(evt);
            }
        });

        botaoLimparHidro.setText("Limpar hidromassagem");
        botaoLimparHidro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimparHidroActionPerformed(evt);
            }
        });

        botaoMordomo.setText("Chamar Mordomo");
        botaoMordomo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMordomoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(botaoVoltar)
                            .addGap(10, 10, 10)
                            .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(50, 50, 50)
                            .addComponent(botaoLimpeza, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(botaoTrocarChuveiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoAbastecerToalha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoServico, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                        .addComponent(botaoLimparHidro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoMordomo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoVoltar))
                .addGap(18, 18, 18)
                .addComponent(botaoLimpeza)
                .addGap(18, 18, 18)
                .addComponent(botaoTrocarChuveiro)
                .addGap(18, 18, 18)
                .addComponent(botaoAbastecerToalha)
                .addGap(18, 18, 18)
                .addComponent(botaoServico)
                .addGap(18, 18, 18)
                .addComponent(botaoLimparHidro, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botaoMordomo)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void botaoLimpezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLimpezaActionPerformed
        new QuartoManu(this.quarto, 1).setVisible(true);
    }//GEN-LAST:event_botaoLimpezaActionPerformed

    private void botaoTrocarChuveiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoTrocarChuveiroActionPerformed
        new QuartoManu(this.quarto, 2).setVisible(true);
    }//GEN-LAST:event_botaoTrocarChuveiroActionPerformed

    private void botaoAbastecerToalhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAbastecerToalhaActionPerformed
        new QuartoManu(this.quarto, 3).setVisible(true);
    }//GEN-LAST:event_botaoAbastecerToalhaActionPerformed

    private void botaoServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoServicoActionPerformed
        new QuartoManu(this.quarto, 4).setVisible(true);
    }//GEN-LAST:event_botaoServicoActionPerformed

    private void botaoLimparHidroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLimparHidroActionPerformed
        new QuartoManu(this.quarto, 5).setVisible(true);
    }//GEN-LAST:event_botaoLimparHidroActionPerformed

    private void botaoMordomoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMordomoActionPerformed
        new QuartoManu(this.quarto, 6).setVisible(true);
    }//GEN-LAST:event_botaoMordomoActionPerformed
    /**
     * @param args the command line arguments
     */

    private ListaQuarto quarto;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAbastecerToalha;
    private javax.swing.JButton botaoLimparHidro;
    private javax.swing.JButton botaoLimpeza;
    private javax.swing.JButton botaoMordomo;
    private javax.swing.JButton botaoServico;
    private javax.swing.JButton botaoTrocarChuveiro;
    private javax.swing.JToggleButton botaoVoltar;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables

    
}
