/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import Quartos.*;
import gravacao.GravarArquivo;
import java.io.IOException;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Igor Paraiso
 */
public class QuartoManu extends javax.swing.JFrame {

    /**
     * Creates new form escolherQuarto
     */
    public QuartoManu(ListaQuarto quarto, int idServico) {
        this.quarto = quarto;
        initComponents();
        setLocationRelativeTo(null);
        this.idServico = idServico;
        switch(idServico){
            case 1:
                this.tituloServico.setText("Escolha o quarto a ser limpo");
                break;
            case 2:
                this.tituloServico.setText("Escolha o quarto que precisa de troca de chuveiro");
                break;
            case 3:
                this.tituloServico.setText("Escolha o quarto que precisa de toalhas");
                break;
            case 4:
                this.tituloServico.setText("Escolha o quarto que precisa de atendimento");
                break;
            case 5:
                this.tituloServico.setText("Escolha o quarto que a Hidro precisa ser limpa");
                break;
            case 6:
                this.tituloServico.setText("Escolha o quarto que precisa de atendimento do Mordomo");
                break;
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloServico = new javax.swing.JLabel();
        botaoAcao = new javax.swing.JToggleButton();
        botaoVoltar = new javax.swing.JToggleButton();
        escolherQuarto = new javax.swing.JComboBox<>();
        msgErro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botaoAcao.setText("Solicitar");
        botaoAcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAcaoActionPerformed(evt);
            }
        });

        botaoVoltar.setText("Voltar");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        escolherQuarto.setModel(new DefaultComboBoxModel(this.quarto.quartoNums()));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botaoVoltar)
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(escolherQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(botaoAcao, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tituloServico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(msgErro, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(tituloServico, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botaoVoltar)))
                .addGap(41, 41, 41)
                .addComponent(escolherQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(botaoAcao)
                .addGap(34, 34, 34)
                .addComponent(msgErro, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void botaoAcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAcaoActionPerformed
        int numQ = this.escolherQuarto.getSelectedIndex();
        
        switch(this.idServico){
            case 1:
                this.quarto.getQuarto(numQ).limpar();
                gravar(this.quarto);
                this.dispose();
                break;
            case 2:
                this.quarto.getQuarto(numQ).TrocarChuveiro();
                gravar(this.quarto);
                this.dispose();
                break;
            case 3:
                this.quarto.getQuarto(numQ).AbastecerToalha();
                gravar(this.quarto);
                this.dispose();
                break;
            case 4:
                if(this.quarto.getQuarto(numQ) instanceof QuartoConfort quartoConfort){
                    quartoConfort.chamarServico();
                    gravar(this.quarto);
                    this.dispose();
                } else {
                    this.msgErro.setText("Esse serviço não está disponível para esse quarto");
                }
                break;

            case 5:
                if(this.quarto.getQuarto(numQ) instanceof QuartoConfort quartoConfort && quartoConfort.isHidro()){
                    quartoConfort.limparHidro();
                    gravar(this.quarto);
                    this.dispose();
                } else {
                    this.msgErro.setText("Esse serviço não está disponível para esse quarto");
                }
                break;
            case 6:
                if(this.quarto.getQuarto(numQ) instanceof QuartoMaster quartoMaster && quartoMaster.isMordomo()){
                    quartoMaster.chamarMordomo();
                    gravar(this.quarto);
                    this.dispose();
                } else {
                    this.msgErro.setText("Esse serviço não está disponível para esse quarto");
                }
                break;
        }
    }//GEN-LAST:event_botaoAcaoActionPerformed

    /**
     * @param args the command line arguments
     */
    
    private ListaQuarto quarto;
    private int idServico;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton botaoAcao;
    private javax.swing.JToggleButton botaoVoltar;
    private javax.swing.JComboBox<String> escolherQuarto;
    private javax.swing.JLabel msgErro;
    private javax.swing.JLabel tituloServico;
    // End of variables declaration//GEN-END:variables
    private void gravar(ListaQuarto list) {
        GravarArquivo gravar;
            try {
                gravar = new GravarArquivo("quartos.txt");
                gravar.grava(list.toString());
                gravar.fecha();
                this.dispose();
            } catch (IOException ex) {
                this.msgErro.setText("Nao foi possivel salvar");
                this.msgErro.setVisible(true);
            }
    }

}
