/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import Quartos.ListaQuarto;
import Quartos.QuartoSimples;
import usuario.Usuario;

/**
 *
 * @author aluno.laboratorio
 */
public class CriarQuartoSimples extends javax.swing.JFrame {

    /**
     * Creates new form CriarQuartoSimples
     */
    public CriarQuartoSimples(ListaQuarto lista) {
        initComponents();
        setLocationRelativeTo(null);
        this.list = lista;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotaoVoltar = new javax.swing.JButton();
        BotaoSalvar = new javax.swing.JButton();
        LabelAndar = new javax.swing.JLabel();
        LabelIdentificador = new javax.swing.JLabel();
        LabelQntHosp = new javax.swing.JLabel();
        LabelTipocama = new javax.swing.JLabel();
        LabelCafemanha = new javax.swing.JLabel();
        LabelVista = new javax.swing.JLabel();
        campoAndar = new javax.swing.JTextField();
        campoIdentificador = new javax.swing.JTextField();
        campoQntHosp = new javax.swing.JTextField();
        campoTipoCama = new javax.swing.JTextField();
        campoCafeManha = new javax.swing.JTextField();
        campoVista = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BotaoVoltar.setText("Voltar");
        BotaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoVoltarActionPerformed(evt);
            }
        });

        BotaoSalvar.setText("Salvar");
        BotaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoSalvarActionPerformed(evt);
            }
        });

        LabelAndar.setText("Andar");

        LabelIdentificador.setText("Letra do Quarto");

        LabelQntHosp.setText("Quantidade de Hospedes");

        LabelTipocama.setText("Tipo de cama");

        LabelCafemanha.setText("Cafe da manha");

        LabelVista.setText("Vista do Quarto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BotaoVoltar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(BotaoSalvar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelQntHosp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campoQntHosp, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(LabelAndar)
                                        .addGap(68, 68, 68))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LabelIdentificador)
                                        .addGap(20, 20, 20)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(campoIdentificador, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                                    .addComponent(campoAndar)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelTipocama)
                                    .addComponent(LabelCafemanha)
                                    .addComponent(LabelVista))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(campoVista, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                                    .addComponent(campoCafeManha)
                                    .addComponent(campoTipoCama))))))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BotaoVoltar)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelAndar)
                    .addComponent(campoAndar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelIdentificador)
                    .addComponent(campoIdentificador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelQntHosp)
                    .addComponent(campoQntHosp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelTipocama)
                    .addComponent(campoTipoCama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelCafemanha)
                    .addComponent(campoCafeManha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelVista)
                    .addComponent(campoVista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(BotaoSalvar)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoVoltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_BotaoVoltarActionPerformed

    private void BotaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoSalvarActionPerformed
        
        char identificador = this.campoIdentificador.getText().charAt(0);
        
        boolean reservado = false;
        Usuario usuario = new Usuario();
        boolean limpo = true;
        boolean checkin = false;
        String tipoCama = this.campoTipoCama.getText();
        boolean cafeDaManha = Boolean.parseBoolean(this.campoCafeManha.getText());
        String vista = this.campoVista.getText();
        float fatura = 0;
        
        try {
            int andar = Integer.parseInt(this.campoAndar.getText());
            int qntHosp = Integer.parseInt(this.campoQntHosp.getText());
            QuartoSimples quarto = new QuartoSimples(andar, identificador, qntHosp, reservado,
			usuario, limpo, checkin, tipoCama, cafeDaManha, vista, fatura);
            this.list.CadastrarSimples(quarto);
        } catch (NumberFormatException e){
            
        }
        
    }//GEN-LAST:event_BotaoSalvarActionPerformed

    
    private ListaQuarto list;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoSalvar;
    private javax.swing.JButton BotaoVoltar;
    private javax.swing.JLabel LabelAndar;
    private javax.swing.JLabel LabelCafemanha;
    private javax.swing.JLabel LabelIdentificador;
    private javax.swing.JLabel LabelQntHosp;
    private javax.swing.JLabel LabelTipocama;
    private javax.swing.JLabel LabelVista;
    private javax.swing.JTextField campoAndar;
    private javax.swing.JTextField campoCafeManha;
    private javax.swing.JTextField campoIdentificador;
    private javax.swing.JTextField campoQntHosp;
    private javax.swing.JTextField campoTipoCama;
    private javax.swing.JTextField campoVista;
    // End of variables declaration//GEN-END:variables
}
