/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import Quartos.ListaQuarto;
import usuario.Usuario;

/**
 *
 * @author aluno.laboratorio
 */
public class CriarQuartoConfort extends javax.swing.JFrame {

    /**
     * Creates new form CriarQuartoConfort
     */
    public CriarQuartoConfort(ListaQuarto lista) {
        initComponents();
        setLocationRelativeTo(null);
        this.list = lista;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotaoVoltar = new javax.swing.JButton();
        BotaoSalvar = new javax.swing.JButton();
        labelAndar = new javax.swing.JLabel();
        labelIdentificador = new javax.swing.JLabel();
        labelQntHosp = new javax.swing.JLabel();
        labelTipoCama = new javax.swing.JLabel();
        labelCafeManha = new javax.swing.JLabel();
        labelVista = new javax.swing.JLabel();
        labelHidro = new javax.swing.JLabel();
        campoAndar = new javax.swing.JTextField();
        campoIdentificador = new javax.swing.JTextField();
        campoQntHosp = new javax.swing.JTextField();
        campoTipoCama = new javax.swing.JTextField();
        campoCafeManha = new javax.swing.JTextField();
        campoVista = new javax.swing.JTextField();
        campoHidro = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BotaoVoltar.setText("Voltar");
        BotaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoVoltarActionPerformed(evt);
            }
        });

        BotaoSalvar.setText("Salvar");
        BotaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoSalvarActionPerformed(evt);
            }
        });

        labelAndar.setText("Andar");

        labelIdentificador.setText("Letra do Quarto");

        labelQntHosp.setText("Quantidade de hóspedes");

        labelTipoCama.setText("Tipo de Cama");

        labelCafeManha.setText("Cafe da manha");

        labelVista.setText("Vista do Quarto");

        labelHidro.setText("Quarto tem Hidro");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BotaoVoltar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(BotaoSalvar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelQntHosp)
                                    .addComponent(labelTipoCama)
                                    .addComponent(labelCafeManha)
                                    .addComponent(labelVista)
                                    .addComponent(labelHidro))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoQntHosp)
                                    .addComponent(campoTipoCama)
                                    .addComponent(campoCafeManha)
                                    .addComponent(campoVista)
                                    .addComponent(campoHidro)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelAndar)
                                    .addComponent(labelIdentificador))
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoIdentificador)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(campoAndar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addGap(107, 107, 107))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BotaoVoltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAndar)
                    .addComponent(campoAndar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIdentificador)
                    .addComponent(campoIdentificador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelQntHosp)
                    .addComponent(campoQntHosp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTipoCama)
                    .addComponent(campoTipoCama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCafeManha)
                    .addComponent(campoCafeManha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelVista)
                    .addComponent(campoVista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelHidro)
                    .addComponent(campoHidro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotaoSalvar)
                .addGap(61, 61, 61))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoVoltarActionPerformed
       this.dispose();
    }//GEN-LAST:event_BotaoVoltarActionPerformed

    private void BotaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoSalvarActionPerformed
        int andar = Integer.parseInt(this.campoAndar.getText());
        char indentficador = this.campoIdentificador.getText().charAt(0);
        boolean reservado = false;
        Usuario usuario = new Usuario();
        boolean limpo = true;
        boolean checkin = false;
        String tipoCama = this.campoTipoCama.getText();
        boolean cafeDaManha = Boolean.parseBoolean(this.campoCafeManha.getText());
        String vista = this.campoVista.getText();
        float fatura = 0;
        boolean hidro = Boolean.parseBoolean(this.campoHidro.getText());
    }//GEN-LAST:event_BotaoSalvarActionPerformed

    private ListaQuarto list;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoSalvar;
    private javax.swing.JButton BotaoVoltar;
    private javax.swing.JTextField campoAndar;
    private javax.swing.JTextField campoCafeManha;
    private javax.swing.JTextField campoHidro;
    private javax.swing.JTextField campoIdentificador;
    private javax.swing.JTextField campoQntHosp;
    private javax.swing.JTextField campoTipoCama;
    private javax.swing.JTextField campoVista;
    private javax.swing.JLabel labelAndar;
    private javax.swing.JLabel labelCafeManha;
    private javax.swing.JLabel labelHidro;
    private javax.swing.JLabel labelIdentificador;
    private javax.swing.JLabel labelQntHosp;
    private javax.swing.JLabel labelTipoCama;
    private javax.swing.JLabel labelVista;
    // End of variables declaration//GEN-END:variables
}
